baseURL = 'https://darkolabs.io/'
languageCode = 'en-us'
title = 'Darko Labs'

[markup.goldmark.renderer]
  unsafe = true

[params]
	customCSS = ["css/tetris.css"]

[menu]
	[[menu.main]]
	  name = "Home"
	  url = "/"
	  weight = 1
	[[menu.main]]
	  name = "Arcade"
	  url = "/arcade/"
	  weight = 3
	[[menu.main]]
	  name = "Tetris"
	  url = "/arcade/tetris"
	  weight = 10
	  parent="Arcade"
	[[menu.main]]
	  name = "Tools"
	  url = "/tools/"
	  weight = 6
	[[menu.main]]
	  name = "Resources"
	  url = "/tools/"
	  weight = 7
	[[menu.main]]
	  name = "EMC2"
	  url = "/emc2/"
	  parent ="Resources"
	  weight = 5
	[[menu.main]]
		name = "EMC2 Timeline - Sonnet 3.5"
		url = "/emc2/timeline-sonnet-35/"
		parent ="Resources"
		weight = 5
	[[menu.main]]
		name = "EMC2 Timeline - GPT-4o1"
		url = "/emc2/timeline-gpt4o1/"
		parent ="Resources"
		weight = 5
	[[menu.main]]
		name = "EMC2 Timeline - Interactive"
		url = "/emc2/timeline-interactive/"
		parent ="Resources"
		weight = 5
	[[menu.main]]
	  name = "Gunnerbench"
	  url = "/gunnerbench/"
	  parent ="Resources"
	  weight = 10
	[[menu.main]]
	  name = "The Thinking Hard Prompt"
	  url = "/tools/think/"
	  parent ="Tools"
	  weight = 18
	 [[menu.main]]
	   name = "The Shrodinger Syndicate"
	   url = "/tools/shrodinger/"
	   parent ="Tools"
	   weight = 19 
	[[menu.main]]
	  name = "Term Surrounder"
	  url = "/tools/ts/"
	  parent ="Tools"
	  weight = 20
	 

